### ISSUE TITLE
option to remove :root variables

### ISSUE THREAD

**Issue by jonathanong** [reworkcss/rework-vars#1]
just moving here from https://github.com/visionmedia/rework/issues/51

**Comment by necolas** [comment]
What kind of API do we want for this? At the moment, a map of vars is the only argument that the plugin accepts.

**Comment by jonathanong** [comment]
oh crap, that's right. it would have to be `rework.use(vars(map, opts))`. 

i'm just going to close this since i don't care anymore :D

**Comment by necolas** [comment]
I care though. We're planning to use this at Twitter and need to strip this excess code for the prod bundles. May as well be handled by the plugin itself.

I wanted to know what kind of API is preferred, or convention in Rework. Using `var(map, opts)` avoids a breaking change to the API but then you have to pass an empty object for `map` just to set the var-stripping option. My preference would be for a forward-facing API change. Anyway, let me know what you guys think.

**Comment by tj** [comment]
we could leave `(map)` and just strip the root stuff by default

**Comment by jonathanong** [comment]
is there even a purpose for the `:root` stuff to remain there? i assumed you guys wanted it in because it'll be in the CSS spec later. stripping by default is what i would prefer.

**Comment by necolas** [comment]
It would be good enough to strip the var declarations until there's a clear reason why you might not want to. Can't think of one at the moment.

But let's not strip `:root` rules, just any appearance of `var-x: value` declarations.

**Comment by jonathanong** [comment]
sounds fine to me!

**Comment by tj** [comment]
yeah the original plan was to strip the `var-*`s and then any empty rules
