### ISSUE TITLE
Create and npm-publish a new release

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-vars#13]
Some new features in `master` (thanks for the quick reviews and merges!) look to necessitate a major version bump.

Variable overwriting: this change would break any apps that assume all variable values are defined and locked prior to substitution occurring.

Variable definition stripping: if any down-stream plugins expect the definitions to remain in the CSS, then they'll also break.

**Comment by tj** [comment]
boom 1.1.0! add you to the npm project too

**Comment by necolas** [comment]
Thanks TJ!
