### ISSUE TITLE
Handle var in media queries definition

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-vars#19]
Here is my code using `rework-vars`

``` css
:root {
  var-bkp-small: 30rem;
}

@media (min-width: var(bkp-small)) {
  html { background: red; }
}
```

the `var(bkp-small)` in the `@media` definition is not parsed, is this on purpose ?

**Comment by necolas** [comment]
Yes, CSS custom properties can only be used in declarations. There's no W3C plans (that I know of) for dealing with media queries.

You can look into using the breakpoints plugin - https://github.com/reworkcss/rework-breakpoints - but it is currently quite limited I'm afraid.

**Comment by JimBobSquarePants** [comment]
It looks like they are probably coming in level 2. 

I can only imagine there are a lot of people looking for this feature; it's pretty much a show-stopper for me.

http://lists.w3.org/Archives/Public/www-style/2013May/0638.html

http://lists.w3.org/Archives/Public/www-style/2013May/0783.html

```
Variables for Media Queries
---------------------------

   Topic: DRYing up Media Queries
   <glazou> http://lists.w3.org/Archives/Public/www-style/2013May/0638.html
   glazou: Wide discussion on mailing list about this
   TabAtkins: Boils down to fact that we do want to do something similar
              to the suggestion, but not right now.
   glazou: I'm using Media Queries a lot for responsive design support in
           BlueGriffon
   * smfr would like to know what DRYing is
   <fantasai> Don't Repeat Yourself
   TabAtkins: Something for level 2?
   glazou: OK noted
```

**Comment by necolas** [comment]
There are already 2 other Rework plugins that let you do this (admittedly, not in an ideal fashion) - rework-breakpoints and rework-variables.

**Comment by MoOx** [comment]
rework-breakpoints recently get custom syntax support @necolas :)
But it would be really cool to get variable support in native media queries as well !

**Comment by necolas** [comment]
> But it would be really cool to get variable support in native media queries as well !

What do you mean?

**Comment by MoOx** [comment]
Make this interpreted by rework-vars:

``` css
:root {
  var-size-small: 30rem;
}
@media (min-width: var(size-small)) {

}
```

**Comment by necolas** [comment]
I have previously explained why we're not doing that in this module: because it breaks with the CSS custom properties spec and the plans of the W3C to avoid using the `var()` construct in media query values.

**Comment by MoOx** [comment]
Yeah but like said on [this previous comment](https://github.com/reworkcss/rework-vars/issues/19#issuecomment-32881323) it seems he have a chance to see that some day...
Anyway, I'm using rework-breakpoints with custom syntax for now.

**Comment by necolas** [comment]
Sure. Reading that thread suggested that they were not going to use the same construct to handle media query placeholders. So it will be best to avoid using rework-vars for that purpose at this point in time.

**Comment by simonsmith** [comment]
It does look as though some plans now exist for how media queries can be dealt with - http://dev.w3.org/csswg/mediaqueries-4/#custom-mq

Worth looking into?

**Comment by necolas** [comment]
See https://github.com/suitcss/suit/issues/51

**Comment by MoOx** [comment]
@necolas which #51 are you refering to ?

**Comment by simonsmith** [comment]
@MoOx https://github.com/suitcss/suit/issues/51

**Comment by MoOx** [comment]
@simonsmith Thanks !
