### ISSUE TITLE
:root { ... } retained in output if it contains comments

### ISSUE THREAD

**Issue by bclinkinbeard** [reworkcss/rework-vars#23]
Just a question as to whether or not this is expected/desired behavior. My bundle ends up with the block below at the top of it. Could/should it be removed?

``` css
:root {
  /* global spacing*/
  /* font colors*/
}
```

**Comment by jonathanong** [comment]
sounds like something a minifier should handle. people are going to complain if their comments are suddenly gone.

**Comment by bclinkinbeard** [comment]
Even though the var declarations are removed? Comments in the absence of what they are describing seem pretty pointless.

**Comment by jonathanong** [comment]
yeah, but it's harmless. i'd rather mitigate the possibility of anyone complaining haha

**Comment by bclinkinbeard** [comment]
Fair enough.

**Comment by necolas** [comment]
> sounds like something a minifier should handle

yup
