### ISSUE TITLE
Update declaration syntax according to spec (eg `var-foo` is now `--foo`)

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-vars#26]
> The syntax of custom properties (CSS variables) was changed from `var-foo` to `--foo`.

http://dev.w3.org/csswg/css-variables/#changes

**Comment by necolas** [comment]
hah, what?

**Comment by necolas** [comment]
not sure what the reasoning was. i will wait to see if this gets reverted, as it's only in the editor's draft at the moment.

**Comment by jonathanong** [comment]
wow. that is so ugly. i wish they can just do `$foo` or something.

**Comment by MoOx** [comment]
I've to admit i like the idea of having the same var name in the declaration & when you use it.
PostCSS already has an implementation https://github.com/iamvdo/postcss-vars :)

**Comment by jonathanKingston** [comment]
Hmm if they are going to change it surely `thing` would be suitable as variable usage is with: `var(thing)` and take the hit for users being able to declare native variables as and when they exist etc.

**Comment by tj** [comment]
the fuck

**Comment by necolas** [comment]
> PostCSS already has an implementation

It's basically a port of this module.

**Comment by jonathanKingston** [comment]
Trying to remember my freenode login so I can ask the author of the changes myself.

**Comment by jonathanKingston** [comment]
I get it more after reading this message from the author:
http://lists.w3.org/Archives/Public/www-style/2014Mar/0261.html

Less that they are variables and more scoped properties.

Looks like FireFox will be shipping soon with this syntax from this syntax also.

**Comment by necolas** [comment]
That thread is what bike-shedding looks like.

We'll just have to wait and make adjustments if necessary.

**Comment by jonathanKingston** [comment]
@necolas I think it is worth simplifying as much as possible, I get that it may appear to be splitting hairs a little bit but the least amount of "Yeah but LESS/SASS/Stylus is so much easier" arguments the more it will be adopted. I get the W3C have lots of issues to tackle and many vested interests in older technologies they want legacy support for however I still think its worth fighting this one.

If enough people chip in now I suspect it could be changed again to something nicer: http://lists.w3.org/Archives/Public/www-style/2014Mar/0590.html I would appreciate it if others got involved too even if we are bike-shedding.

**Comment by necolas** [comment]
> I think it is worth simplifying as much as possible

It has to be the right kind of simplification though. I see you proposed not using `var()`, but then you can't specify a fallback and the feature becomes less useful.

I don't think there's value for me to get involved in the mailing list discussion. My input is unlikely to make a difference either way.

**Comment by MoOx** [comment]
Thanks a lot @necolas.
