### ISSUE TITLE
Variables not parsed when inside of pseudoclasses

### ISSUE THREAD

**Issue by VinSpee** [reworkcss/rework-vars#35]
I recently tried out http://github.com/mr0grog/element-query and found that rework-vars doesn't parse variables defined inside pseudoclasses. Example:

`.User:where(min-available-width: var(--User-medium))`

Is not parsed correctly and yields 

`.User:where(min-available-width: var(--User-medium))`

as a result.

**Comment by MoOx** [comment]
This is just not valid CSS.

> The var() function can be used in place of any part of a value in any property on an element.
> **The var() function _can not_ be used as property names, selectors, or anything else besides property values.**

From: http://www.w3.org/TR/css-variables/#using-variables

**Comment by MoOx** [comment]
Is there any spec for those element queries ?
At the first look [rework-custom-media](https://github.com/reworkcss/rework-custom-media) seems a better place to ask for that (if there is at least a draft of the future spec).
Or maybe a _rework-element-queries_ can do the thing.

**Comment by VinSpee** [comment]
no, there's currently not a spec, but it's in the [use cases and requirements stage](http://responsiveimagescg.github.io/eq-usecases/). Thanks for clarifying!
