### ISSUE TITLE
idea: local vars set with `:local` selector

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-vars#36]
Not sure this is a good idea (because it's not part of CSS), but I've found myself wanting to define local variables (a la JS) within a file.

**Comment by necolas** [comment]
Going to implement this behind a new options flag. It will simply add support for `:local` as well as `:root`, rather than defining specific semantics for `:local` at this point in time.

**Comment by simonsmith** [comment]
Is the idea for this to behave the same as `:root` except it can't be accessed/overridden from other files? It looks like `:root` and `:local` are the same in that PR, is that the goal for now?
