### ISSUE TITLE
Add support for fallback values

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-vars#8]
This is another ape-ing of the CSS draft spec. Handy for customisable component development.

Original:

``` css
.my-component {
  color: var(my-component-color, #ff0);
}
```

Yields (when no `var-my-component-color` exists):

``` css
.my-component {
  color: #ff0;
}
```

Details:

> The second argument to the [`var()`] function, if provided, is a fallback value, which is used as the substitution value when the referenced variable is invalid.
> 
> Note: The syntax of the fallback, like that of custom properties, allows commas. For example, `var(foo, red, blue)` defines a fallback of `red, blue`; that is, anything between the first comma and the end of the function is considered a fallback value.
> 
> A property value containing a variable must be assumed to be valid at parse time. It is only syntax-checked at computed-value time, after variable references have been resolved.
> 
> To resolve a variable in a property's value:
> 
> If the variable named by the first argument to the `var()` function is a valid variable, replace the `var()` function by the value of the corresponding custom property.
> 
> Otherwise, if the `var()` function has a fallback value as its second argument, replace the `var()` function by the fallback value. If there are any `var()` references in the fallback, resolve them as well.
> 
> Otherwise, the property containing the `var()` function is invalid at computed-value time.

Source: http://www.w3.org/TR/css-variables/

**Comment by tj** [comment]
sounds good!
